name: CI - test convert utility		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4

      - name: Build Convert
        run: gcc -o convert main.c convert.c utils.c

      - name: Upload Convert Executable
        uses: actions/upload-artifact@v4
        with:
          name: convert
          path: ./convert


      - name: Build Testing Executable with Coverage
        run: make ctest


      - name: Run Tests
        run: ./test_script > test_results.txt


      - name: Generate Coverage Reports
        run: gcov ctest-convert.c; gcov ctest-main.c; gcov ctest-utils.c


      - name: Upload Test Results and Coverage
        if: ${{ always()}}
        
        uses: actions/upload-artifact@v4
        with:
          name: Test Results and Coverage
          path: |
          test_results.txt
          convert.c.gcov
          main.c.gcov
          utils.c.gcov
